# Generated by Django 5.1.5 on 2026-03-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='window_after',
            field=models.PositiveIntegerField(default=2, help_text='Days after planned_day that the visit is allowed.'),
        ),
        migrations.AddField(
            model_name='visit',
            name='window_before',
            field=models.PositiveIntegerField(default=2, help_text='Days before planned_day that the visit is allowed.'),
        ),
    ]
