# Generated by Django 5.1.5 on 2026-06-17 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_add_visit_window_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forminstance',
            name='submission_uuid',
            field=models.UUIDField(blank=True, help_text='Client-generated UUID for offline deduplication.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='cross_field_validation',
            field=models.JSONField(blank=True, help_text='JSONB — cross-field rules, e.g. {"gte": "CONSENT_DATE", "message": "Must be on or after consent date"}', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='display_condition',
            field=models.JSONField(blank=True, help_text='JSONB — skip logic condition. Field is shown only when this evaluates true. Format: {"field": "ENROLLED", "operator": "eq", "value": "1"} Operators: eq, neq, in, gt, lt, gte, lte, not_empty.', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Section header — items with the same section are visually grouped.', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='validation_rule',
            field=models.CharField(blank=True, default='', help_text='Regex or custom validation rule, e.g. range(0, 59).', max_length=500),
        ),
        migrations.CreateModel(
            name='ItemResponseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('reason_for_change', models.CharField(blank=True, default='', help_text='Why was this field changed? Required for submitted CRFs.', max_length=500)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_response_audits', to=settings.AUTH_USER_MODEL)),
                ('item_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='clinical.itemresponse')),
            ],
            options={
                'verbose_name': 'Item Response Audit',
                'verbose_name_plural': 'Item Response Audit Trail',
                'db_table': 'clinical_item_response_audit',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, help_text='If true, this form must be filled at this visit.')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_forms', to='clinical.form')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_forms', to='clinical.visit')),
            ],
            options={
                'verbose_name': 'Visit-Form Mapping',
                'verbose_name_plural': 'Visit-Form Mappings',
                'db_table': 'clinical_visit_forms',
                'unique_together': {('visit', 'form')},
            },
        ),
    ]
