# Generated for HACT CTMS — add OpenClinica Unique Protocol ID field.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_forminstance_submission_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='openclinica_study_identifier',
            field=models.CharField(
                blank=True,
                default='',
                help_text=(
                    "OpenClinica Study 'Unique Protocol ID', e.g. 'HACTPSBIV2'. "
                    "Used by the SOAP web services (subject enrollment, event scheduling). "
                    "This is NOT the S_… OID — OC matches subjects by the Unique Protocol ID."
                ),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name='study',
            name='openclinica_study_oid',
            field=models.CharField(
                blank=True,
                default='',
                help_text=(
                    "OpenClinica Study OID, e.g. 'S_HACTPSBI' (auto-generated by OC). "
                    "Used as the ODM StudyOID when importing form data."
                ),
                max_length=100,
            ),
        ),
    ]
