"""
Management command to test Nextcloud eTMF connectivity and operations.
Usage: python manage.py test_nextcloud
"""

from django.core.management.base import BaseCommand


class Command(BaseCommand):
    help = "Test Nextcloud eTMF connectivity, folder creation, and file upload/download."

    def handle(self, *args, **options):
        from integrations.nextcloud import (
            NC_BASE_URL,
            NC_USER,
            is_available,
            get_server_info,
            create_etmf_structure,
            upload_to_etmf,
            list_etmf_studies,
            list_etmf_documents,
            download_file,
            delete_file,
        )

        self.stdout.write("Testing Nextcloud eTMF connection...")
        self.stdout.write(f"  URL:  {NC_BASE_URL}")
        self.stdout.write(f"  User: {NC_USER}")
        self.stdout.write("")

        # --- Test 1: Availability ---
        if not is_available():
            self.stdout.write(self.style.ERROR(
                "❌ Nextcloud is NOT reachable\n"
                "   Hint: Start with 'docker compose --profile nextcloud up -d'"
            ))
            return

        self.stdout.write(self.style.SUCCESS("✅ Nextcloud is REACHABLE"))

        # --- Test 2: Server Info ---
        info = get_server_info()
        if info:
            self.stdout.write(f"  Version: {info.get('versionstring', 'unknown')}")
            self.stdout.write(f"  Edition: {info.get('edition', 'unknown')}")
        self.stdout.write("")

        # --- Test 3: Create eTMF Structure ---
        self.stdout.write("Creating eTMF structure for test study HACT-TEST...")
        ok = create_etmf_structure("HACT-TEST")
        if ok:
            self.stdout.write(self.style.SUCCESS("  ✅ eTMF folder structure created"))
        else:
            self.stdout.write(self.style.ERROR("  ❌ Failed to create eTMF structure"))
            return

        # --- Test 4: Upload Test Document ---
        self.stdout.write("Uploading test document...")
        test_content = b"HACT CTMS - Nextcloud Integration Test Document\nGenerated by test_nextcloud management command."
        url = upload_to_etmf(
            protocol_number="HACT-TEST",
            category="01_Regulatory",
            filename="integration_test.txt",
            content=test_content,
            content_type="text/plain",
        )
        if url:
            self.stdout.write(self.style.SUCCESS(f"  ✅ File uploaded: {url}"))
        else:
            self.stdout.write(self.style.ERROR("  ❌ File upload failed"))
            return

        # --- Test 5: Download and Verify ---
        self.stdout.write("Downloading and verifying test document...")
        downloaded = download_file("eTMF/HACT-TEST/01_Regulatory/integration_test.txt")
        if downloaded and downloaded == test_content:
            self.stdout.write(self.style.SUCCESS("  ✅ Download verified (content matches)"))
        elif downloaded:
            self.stdout.write(self.style.WARNING("  ⚠️ Downloaded but content differs"))
        else:
            self.stdout.write(self.style.ERROR("  ❌ Download failed"))

        # --- Test 6: List eTMF Studies ---
        self.stdout.write("\nListing eTMF studies...")
        studies = list_etmf_studies()
        for study in studies:
            self.stdout.write(f"  📁 {study}")

        # --- Test 7: List Documents ---
        self.stdout.write("\nListing eTMF documents for HACT-TEST/01_Regulatory...")
        docs = list_etmf_documents("HACT-TEST", "01_Regulatory")
        for doc in docs:
            icon = "📁" if doc["is_dir"] else "📄"
            self.stdout.write(f"  {icon} {doc['name']}")

        # --- Cleanup ---
        self.stdout.write("\nCleaning up test data...")
        delete_file("eTMF/HACT-TEST")
        self.stdout.write(self.style.SUCCESS("  ✅ Test folder removed"))

        self.stdout.write(self.style.SUCCESS("\n✅ Nextcloud eTMF integration test COMPLETE."))
