# Generated by Django 5.1.5 on 2026-03-26 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ae_term', models.CharField(help_text='Adverse event term/description.', max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('serious', models.BooleanField(default=False, help_text='Is this a Serious Adverse Event (SAE)?')),
                ('serious_criteria', models.TextField(blank=True, default='', help_text='Criteria for seriousness (death, hospitalization, etc.).')),
                ('causality', models.CharField(blank=True, choices=[('not_related', 'Not Related'), ('unlikely', 'Unlikely'), ('possible', 'Possible'), ('probable', 'Probable'), ('definite', 'Definite')], default='', max_length=30)),
                ('outcome', models.CharField(blank=True, choices=[('recovered', 'Recovered/Resolved'), ('recovering', 'Recovering/Resolving'), ('not_recovered', 'Not Recovered/Not Resolved'), ('recovered_with_sequelae', 'Recovered/Resolved with Sequelae'), ('fatal', 'Fatal'), ('unknown', 'Unknown')], default='', max_length=30)),
                ('action_taken', models.TextField(blank=True, default='', help_text='Action taken regarding study treatment.')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_adverse_events', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='clinical.study')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='clinical.subject')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adverse Event',
                'verbose_name_plural': 'Adverse Events',
                'db_table': 'safety_adverse_events',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='CiomsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_version', models.CharField(default='1.0', max_length=20)),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('submission_deadline', models.DateField(blank=True, null=True)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('regulatory_authority', models.CharField(blank=True, default='', help_text='Target regulatory authority (e.g., EFDA, FDA).', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], db_index=True, default='draft', max_length=20)),
                ('file_url', models.URLField(blank=True, default='', help_text='Nextcloud URL to the CIOMS PDF document.', max_length=500)),
                ('adverse_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cioms_forms', to='safety.adverseevent')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CIOMS Form',
                'verbose_name_plural': 'CIOMS Forms',
                'db_table': 'safety_cioms_forms',
                'ordering': ['-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='SafetyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('DSUR', 'Development Safety Update Report'), ('DMC', 'Data Monitoring Committee'), ('quarterly', 'Quarterly Safety Report')], max_length=20)),
                ('review_date', models.DateField()),
                ('summary', models.TextField(blank=True, default='')),
                ('file_url', models.URLField(blank=True, default='', help_text='Nextcloud URL to the review document.', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reviews', to='clinical.study')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Review',
                'verbose_name_plural': 'Safety Reviews',
                'db_table': 'safety_reviews',
                'ordering': ['-review_date'],
            },
        ),
    ]
