# Generated by Django 5.1.5 on 2026-06-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseevent',
            name='notified_at_50_pct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='notified_at_90_pct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='reported_to_authority_at',
            field=models.DateTimeField(blank=True, help_text='When the SAE was actually reported to the regulatory authority.', null=True),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='reporting_deadline',
            field=models.DateTimeField(blank=True, help_text='Auto-computed deadline: 7 days (fatal/life-threatening) or 15 days (other SAE).', null=True),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='reporting_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('on_time', 'Reported On Time'), ('overdue', 'Overdue')], db_index=True, default='not_applicable', max_length=20),
        ),
    ]
