# Generated by Django 5.1.5 on 2026-03-26 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('lock', 'Lock'), ('sign', 'Sign')], db_index=True, max_length=20)),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('record_id', models.CharField(blank=True, default='', help_text='Primary key of the affected record.', max_length=50)),
                ('old_value', models.JSONField(blank=True, help_text='JSONB — previous state of the record (for updates/deletes).', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='JSONB — new state of the record (for creates/updates).', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
    ]
