# Generated by Django 5.1.5 on 2026-03-26 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_name', models.CharField(db_index=True, max_length=255)),
                ('result_value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('reference_range_low', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('reference_range_high', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('flag', models.CharField(blank=True, choices=[('H', 'High'), ('L', 'Low'), ('N', 'Normal')], default='', help_text='H=High, L=Low, N=Normal relative to reference range.', max_length=1)),
                ('result_date', models.DateField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_lab_results', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='clinical.subject')),
                ('subject_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='clinical.subjectvisit')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Result',
                'verbose_name_plural': 'Lab Results',
                'db_table': 'lab_results',
                'ordering': ['-result_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_name', models.CharField(db_index=True, max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('all', 'All')], default='all', max_length=5)),
                ('age_lower', models.PositiveIntegerField(blank=True, help_text='Minimum age (inclusive).', null=True)),
                ('age_upper', models.PositiveIntegerField(blank=True, help_text='Maximum age (inclusive).', null=True)),
                ('range_low', models.DecimalField(decimal_places=4, max_digits=10)),
                ('range_high', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='clinical.study')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reference Range',
                'verbose_name_plural': 'Reference Ranges',
                'db_table': 'lab_reference_ranges',
                'ordering': ['test_name'],
            },
        ),
        migrations.CreateModel(
            name='SampleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('senaite_sample_id', models.CharField(blank=True, db_index=True, default='', help_text='SENAITE LIMS sample identifier.', max_length=100)),
                ('collection_date', models.DateField()),
                ('sample_type', models.CharField(help_text='Type of sample (e.g., Blood, Urine, Tissue).', max_length=100)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='collected', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_collections', to='clinical.subject')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sample Collection',
                'verbose_name_plural': 'Sample Collections',
                'db_table': 'lab_sample_collections',
                'ordering': ['-collection_date'],
            },
        ),
    ]
