# Generated by Django 5.1.5 on 2026-03-26 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('missing_data', 'Missing Data Report'), ('out_of_range', 'Out-of-Range Values Report'), ('query_status', 'Query Status Report')], max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField(blank=True, help_text='JSONB — structured report data (summaries, counts, details).', null=True)),
                ('file_url', models.URLField(blank=True, default='', help_text='Nextcloud URL to the full report document.', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_quality_reports', to='clinical.study')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Quality Report',
                'verbose_name_plural': 'Data Quality Reports',
                'db_table': 'outputs_data_quality_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('snapshot_type', models.CharField(choices=[('SDTM', 'SDTM (Study Data Tabulation Model)'), ('ADaM', 'ADaM (Analysis Data Model)'), ('raw', 'Raw Data Export')], max_length=10)),
                ('file_url', models.URLField(blank=True, default='', help_text='Nextcloud URL to the exported dataset file.', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('criteria', models.JSONField(blank=True, help_text='JSONB — export parameters and filters used to generate this snapshot.', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_snapshots', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_snapshots', to='clinical.study')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dataset Snapshot',
                'verbose_name_plural': 'Dataset Snapshots',
                'db_table': 'outputs_dataset_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
